version: "3.8" # Versi Docker Compose file, gunakan versi terbaru yang stabil

services:
  db: # Nama service untuk MySQL
    image: mysql:8.0 # Gunakan image resmi MySQL versi 8
    container_name: be_siakad_mysql # Nama container agar mudah dikenali
    restart: always # Restart container otomatis jika gagal atau Docker restart
    environment: # Variabel lingkungan untuk inisialisasi MySQL – ambil dari env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # Mapping port host 3306 ke port 3306 di container
    volumes:
      - mysql_data:/var/lib/mysql # Simpan data MySQL ke volume agar tidak hilang saat container dihentikan

  phpmyadmin: # Service phpMyAdmin
    image: phpmyadmin/phpmyadmin # Image resmi phpMyAdmin
    container_name: be_siakad_phpmyadmin # Nama container
    restart: always
    ports:
      - "8080:80" # phpMyAdmin bisa diakses melalui http://localhost:8080
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db # Pastikan service db (MySQL) dijalankan lebih dulu

volumes:
  mysql_data: # Volume untuk menyimpan data MySQL secara persisten

