version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: be_siakad_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: be_siakad
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: be_siakad_phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin123
    depends_on:
      - db

  be-siakad:
    build:
      context: ../../
      dockerfile: misc/docker/Dockerfile
    container_name: be_siakad_backend_prod
    restart: always
    env_file:
      - ../../.env
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}

volumes:
  mysql_data:
